name: Website HTML

on:
    push:
        branches: [ main ]
        paths:
        - 'UI/**'
    pull_request:
        branches: [ main ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name cgresume -d '$web' -s UI/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name CustomWebSite --name cgresume --resource-group rg_cg_resume

  # Azure logout 
    - name: logout
      run: |
            az logout
